-- oracle all_sequences table
CREATE TABLE ALL_SEQUENCES (
  SEQUENCE_OWNER VARCHAR2(30),
  SEQUENCE_NAME VARCHAR2(30),
  MIN_VALUE NUMBER(10),
  MAX_VALUE NUMBER(10),
  INCREMENT_BY NUMBER(10),
  CYCLE_FLAG NUMBER(1),
  ORDER_FLAG NUMBER(1),
  CACHE_SIZE NUMBER(10),
  LAST_NUMBER NUMBER(10)
);